FROM node:18-alpine3.17

WORKDIR /opt/app

RUN apk update && \
    apk upgrade --no-cache && \
    apk add --no-cache \
    yarn \
    make \
    g++ 
    
COPY . .
RUN yarn
RUN yarn run prettier -v
RUN yarn run prettier-check
RUN yarn test
RUN yarn tsc