FROM node:lts-alpine as builder

COPY package.json ./
RUN yarn
RUN mkdir /app-ui
RUN mv ./node_modules ./app-ui
WORKDIR /app-ui
COPY . .

ARG DEPLOY_ENV=production
ENV DEPLOY_ENV=${DEPLOY_ENV}

RUN yarn build --mode ${DEPLOY_ENV}

FROM nginx:alpine

COPY ./nginx.conf /etc/nginx/nginx.conf

RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app-ui/dist /usr/share/nginx/html
EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
