---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-portal-production
spec:
  acme:
    email: eng@getskip.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: production-issuer-portal-account-key
    solvers:
      - dns01:
          cloudDNS:
            project: skip-sandbox

